version: '3.8'

services:
  server:
    build: 
      context: ./dockers-files/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./dockers-files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockers-files/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    container_name: nginx_php
    networks:
      - php_nginx
  

  back: 
    build: 
      context: ./dockers-files/php/
      dockerfile: Dockerfile 
    volumes:
      - ./:/var/www/html
    networks:
      - php_nginx

  composer_nginx:
    image: composer:2.7
    working_dir: /var/www/html
    container_name: comp 
    volumes:
      - ./:/var/www/html
    depends_on:
      - back
    networks:
      - php_nginx

  db:
    container_name: postgres_nginx
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${PG_DBNAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - php_nginx
    restart: unless-stopped

networks:
  php_nginx:
    driver: bridge

volumes:
  postgres: